// js/config.js (this will be generated by GitHub Actions)
export const emailConfig = {
  SERVICE_ID: '__SERVICE_ID__',
  TEMPLATE_ID: '__TEMPLATE_ID__', 
  PUBLIC_KEY: '__PUBLIC_KEY__'
};

/*## Setup Instructions

1. Copy `js/config.example.js` to `js/config.js`
2. Add your EmailJS credentials to `js/config.js`
3. Open `index.html` in your browser*/
